---
- name: install apache2 service
  become: yes
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: start the apache2 service
  become: yes
  service:
    name: apache2
    state: started