---
- name: Install lighttpd web server
  become: yes
  apt:
    name: lighttpd
    state: latest
    update_cache: yes

# Included the jinja2 template file
- name: Generate configuration file
  template:
    src: myconfig.j2
    dest: /etc/lighttpd/lighttpd.conf
    owner: root
    group: root
    mode: '0644'
  vars:
    server_port: 9090  #port is passed in jinja2 template dynammically and we can chnage

- name: Start lighttpd service
  become: yes
  service:
    name: lighttpd
    state: started